import type { Metadata } from 'next'
import '@/styles/globals.css'
import Script from 'next/script'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <head>
        <Script strategy="beforeInteractive" src="/pspdfkit/pspdfkit.js" />
      </head>
      <body suppressHydrationWarning>{children}</body>
    </html>
  )
}
